application: devfest-brasil
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico




- url: /assets/(.*)
  static_files: assets/\1
  upload: assets/(.*)


- url: /index\.html
  static_files: index.html
  upload: index\.html

- url: /
  static_files: index_novo.html
  upload: index_novo\.html

libraries:
- name: webapp2
  version: "2.5.1"
